alter table appointment add column appointment_date date;
alter table appointment add column appointment_time time;
alter table appointment add column id_service varchar(255);
alter table users add column gender varchar(255);
alter table appointment add constraint FK5k0oem3ypbsnpc0kt1htx37w4 foreign key (id_service) references services (id);
alter table appointment add column appointment_date date;
alter table appointment add column appointment_time time;
alter table appointment add column id_service varchar(255);
alter table users add column gender varchar(255);
alter table appointment add constraint FK5k0oem3ypbsnpc0kt1htx37w4 foreign key (id_service) references services (id);
alter table appointment add column appointment_date date;
alter table appointment add column appointment_time time;
alter table appointment add column id_service varchar(255);
create table user_roles (user_id varchar(255) not null, roles varchar(255)) engine=InnoDB;
alter table users add column gender varchar(255);
alter table appointment add constraint FK5k0oem3ypbsnpc0kt1htx37w4 foreign key (id_service) references services (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
