FROM amazoncorretto:11-alpine-jdk
MAINTAINER https://github.com/Nerd-Geek/PeluqueriaDAM
COPY target/ServerPeluqueriaDAM-0.0.1-SNAPSHOT.jar ServerPeluqueriaDAM.jar
ENTRYPOINT ["java","-jar","/ServerPeluqueriaDAM.jar"]